### ISSUE TITLE
Need to reinstall the app the start the session

### ISSUE THREAD

**Issue by cuttlefishi** [xmeshlab/xonefi-android#68]
**Issue:** Closing and restarting the app, the session doesn't start.
**Workaround:** Need to reinstall the app to start the session. 

Issue could be in the app startup or the closing procedure.

**Comment by rcookie777** [comment]
I did not notice this issue yesterday when testing , I was able to connect without refreshing the app. I will look into it today.

**Comment by cuttlefishi** [comment]
3074804eedc049c77223dc65bd7a673d8ac4008f
